#!/bin/bash
echo "total 56
drwxr-xr-x 2 kali kali 4096 May 30 05:48 .
drwxr-xr-x 6 kali kali 4096 May 30 04:19 ..
-rwxr-xr-x 1 kali kali   33 May 30 04:27 0-hello_world
-rwxr-xr-x 1 kali kali   29 May 30 04:31 1-confused_smiley
-rwxr-xr-x 1 kali kali   52 May 30 04:41 2-hellofile
-rwxr-xr-x 1 kali kali   66 May 30 04:45 3-twofiles
-rwxr-xr-x 1 kali kali   56 May 30 05:03 4-lastline
-rwxr-xr-x 1 kali kali   56 May 30 05:06 5-firstline
-rwxr-xr-x 1 kali kali   37 May 30 05:25 6-firstline
-rwxr-xr-x 1 kali kali   77 May 30 05:36 7-file
-rwxr-xr-x 1 kali kali   25 May 30 05:47 8-cwd_state
-rw-r--r-- 1 kali kali  743 May 30 05:11 iacta
-rw-r--r-- 1 kali kali    7 May 30 05:43 ls_cwd_content
-rwxr-xr-x 1 kali kali    7 May 30 05:48 x
" > ls_cwd_content 
